2019-11-01 23:01:34,291	INFO	main1	<module>	Line:11	app started
2019-11-01 23:01:34,301	WARNING	_internal	_log	Line:122	 * Debugger is active!
2019-11-01 23:01:34,340	INFO	_internal	_log	Line:122	 * Debugger PIN: 185-856-785
2019-11-01 23:01:34,354	INFO	_internal	_log	Line:122	 * Running on http://192.168.2.210:9100/ (Press CTRL+C to quit)
2019-11-01 23:01:45,127	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:01:45] "GET /Login/logout/22555e98-befc-41ab-82e3-7a151b687f5a/test HTTP/1.1" 200 -
2019-11-01 23:01:51,852	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:01:51] "GET /Login/test/202cb962ac59075b964b07152d234b70 HTTP/1.1" 200 -
2019-11-01 23:01:55,141	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:01:55] "GET /ProblemSet/497925dd-2143-413d-83f9-7edfc2f7ba2e/ww HTTP/1.1" 200 -
2019-11-01 23:01:56,214	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:01:56] "GET /ProblemSet/init/497925dd-2143-413d-83f9-7edfc2f7ba2e/ww HTTP/1.1" 200 -
2019-11-01 23:01:56,236	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:01:56] "GET /ProblemSet/answer/497925dd-2143-413d-83f9-7edfc2f7ba2e/2 HTTP/1.1" 200 -
2019-11-01 23:02:19,684	INFO	_internal	_log	Line:122	 * Detected change in 'C:\\development\\examsystem\\services\\daos\\problemsetDAO.py', reloading
