2019-11-03 23:42:02,328	INFO	main1	<module>	Line:11	app started
2019-11-03 23:42:02,335	WARNING	_internal	_log	Line:122	 * Debugger is active!
2019-11-03 23:42:02,365	INFO	_internal	_log	Line:122	 * Debugger PIN: 185-856-785
2019-11-03 23:42:02,376	INFO	_internal	_log	Line:122	 * Running on http://192.168.2.210:9100/ (Press CTRL+C to quit)
2019-11-03 23:42:17,722	INFO	_internal	_log	Line:122	192.168.2.210 - - [03/Nov/2019 23:42:17] "GET /Login/logout/5801fc56-6473-48e9-b789-cc05108148ab/test HTTP/1.1" 200 -
2019-11-03 23:42:27,328	INFO	_internal	_log	Line:122	192.168.2.210 - - [03/Nov/2019 23:42:27] "GET /Login/test/202cb962ac59075b964b07152d234b70 HTTP/1.1" 200 -
2019-11-03 23:42:58,722	INFO	_internal	_log	Line:122	192.168.2.210 - - [03/Nov/2019 23:42:58] "GET /ProblemSet/dcd82132-ebc2-43b7-9275-491f7f4707d1/ww HTTP/1.1" 200 -
2019-11-03 23:42:59,823	INFO	_internal	_log	Line:122	192.168.2.210 - - [03/Nov/2019 23:42:59] "GET /ProblemSet/init/dcd82132-ebc2-43b7-9275-491f7f4707d1/ww HTTP/1.1" 200 -
2019-11-03 23:42:59,855	INFO	_internal	_log	Line:122	192.168.2.210 - - [03/Nov/2019 23:42:59] "GET /ProblemSet/answer/dcd82132-ebc2-43b7-9275-491f7f4707d1/4 HTTP/1.1" 200 -
2019-11-03 23:43:30,280	INFO	_internal	_log	Line:122	 * Detected change in 'C:\\development\\examsystem\\services\\apis\\problemsetAPI.py', reloading
